### đọc dữ liệu

In [2]:
import pandas as pd

df = pd.read_csv(r"D:\PRO2291_DuAnTopNghiep\PRO2291_duantotnghiep1\data\raw/sales_06_FY2020-21.csv")

df.head()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20640\3516725256.py:3: DtypeWarning: Columns (0: order_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\PRO2291_DuAnTopNghiep\PRO2291_duantotnghiep1\data\raw/sales_06_FY2020-21.csv")

,order_id,order_date,status,item_id,sku,qty_ordered,price,value,discount_amount,total,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Discount_Percent
0,100354678,10/1/2020,received,574772,oasis_Oasis-064-36,21,89.9,1798.0,0.0,1798.0,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
1,100354678,10/1/2020,received,574774,Fantastic_FT-48,11,19.0,190.0,0.0,190.0,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
2,100354680,10/1/2020,complete,574777,mdeal_DMC-610-8,9,149.9,1199.2,0.0,1199.2,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
3,100354680,10/1/2020,complete,574779,oasis_Oasis-061-36,9,79.9,639.2,0.0,639.2,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0
4,100367357,11/13/2020,received,595185,MEFNAR59C38B6CA08CD,2,99.9,99.9,0.0,99.9,...,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus,0.0

# Kiểm tra kiểu dữ liệu

In [3]:
df.info() #Kiểm tra kiểu dữ liệu

<class 'pandas.DataFrame'>
RangeIndex: 286392 entries, 0 to 286391
Data columns (total 36 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          286392 non-null  object
 1   order_date        286392 non-null  str
 2   status            286392 non-null  str
 3   item_id           286392 non-null  int64
 4   sku               286392 non-null  str
 5   qty_ordered       286392 non-null  int64
 6   price             286392 non-null  float64
 7   value             286392 non-null  float64
 8   discount_amount   286392 non-null  float64
 9   total             286392 non-null  float64
 10  category          286392 non-null  str
 11  payment_method    286392 non-null  str
 12  bi_st             286392 non-null  str
 13  cust_id           286392 non-null  int64
 14  year              286392 non-null  int64
 15  month             286392 non-null  str
 16  ref_num           286392 non-null  int64
 17  Name Prefix       286392 non-null  str
 18  First Name        286392 non-null  str
 19  Middle Initial    286392 non-null  str
 20  Last Name         286392 non-null  str
 21  Gender            286392 non-null  str
 22  age               286392 non-null  int64
 23  full_name         286392 non-null  str
 24  E Mail            286392 non-null  str
 25  Customer Since    286392 non-null  str
 26  SSN               286392 non-null  str
 27  Phone No.         286392 non-null  str
 28  Place Name        286392 non-null  str
 29  County            286392 non-null  str
 30  City              286392 non-null  str
 31  State             286392 non-null  str
 32  Zip               286392 non-null  int64
 33  Region            286392 non-null  str
 34  User Name         286392 non-null  str
 35  Discount_Percent  286392 non-null  float64
dtypes: float64(5), int64(7), object(1), str(23)
memory usage: 78.7+ MB

In [4]:
df.isnull().sum() #Kiểm tra null

order_id            0
order_date          0
status              0
item_id             0
sku                 0
qty_ordered         0
price               0
value               0
discount_amount     0
total               0
category            0
payment_method      0
bi_st               0
cust_id             0
year                0
month               0
ref_num             0
Name Prefix         0
First Name          0
Middle Initial      0
Last Name           0
Gender              0
age                 0
full_name           0
E Mail              0
Customer Since      0
SSN                 0
Phone No.           0
Place Name          0
County              0
City                0
State               0
Zip                 0
Region              0
User Name           0
Discount_Percent    0
dtype: int64

In [5]:
df.duplicated().sum() #Kiểm tra duplicate

np.int64(0)

In [6]:
df.describe() #Thống kê

,item_id,qty_ordered,price,value,discount_amount,total,cust_id,year,ref_num,age,Zip,Discount_Percent
count,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000
mean,741664.902131,3.011296,851.385253,885.879934,70.039427,815.840507,70048.019054,2020.618778,560853.663395,46.489033,49723.160015,6.069079
std,95746.031827,4.573837,1741.750751,2073.252179,256.880870,1983.580302,30243.856395,0.485688,255828.418398,16.673288,27597.198873,10.100100
min,574769.000000,1.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2020.000000,111127.000000,18.000000,210.000000,0.000000
25%,659684.500000,2.000000,49.900000,49.900000,0.000000,49.900000,56519.000000,2020.000000,341265.000000,32.000000,26571.750000,0.000000
50%,742309.000000,2.000000,119.000000,158.970000,0.000000,149.800000,74225.500000,2021.000000,564857.000000,47.000000,49316.000000,0.000000
75%,826124.250000,3.000000,950.000000,910.000000,18.383050,800.000000,92357.000000,2021.000000,781086.000000,61.000000,72645.000000,11.000000
max,905208.000000,501.000000,101262.590000,101262.590000,30213.150000,101262.590000,115326.000000,2021.000000,999981.000000,75.000000,99950.000000,75.000000